### ISSUE TITLE
ilp-ws-reconnect debug websocket disconnected with Error: connect ECONNREFUSED 127.0.0.1:7768; reconnect in 5000

### ISSUE THREAD

**Issue by PaulRBerg** [interledgerjs/moneyd-gui#6]
I have made sure that the port is open. Full stack:

```
2018-05-08T11:20:40.821Z ilp-ws-reconnect debug websocket disconnected with Error: connect ECONNREFUSED 127.0.0.1:7768; reconnect in 5000
(node:16333) UnhandledPromiseRejectionWarning: Error: connection aborted
    at AbstractBtpPlugin.once (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/ilp-plugin-btp/index.js:215:21)
    at Object.onceWrapper (events.js:254:19)
    at AbstractBtpPlugin.emit (events.js:159:13)
    at AbstractBtpPlugin._emitDisconnect (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/ilp-plugin-btp/index.js:472:12)
    at WebSocketReconnector._ws.on (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/ilp-plugin-btp/index.js:200:39)
    at WebSocketReconnector.EventEmitter.emit (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/eventemitter2/lib/eventemitter2.js:351:19)
    at WebSocketReconnector._reconnect (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/ilp-plugin-btp/ws-reconnect.js:33:10)
    at WebSocket._instance.on (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/ilp-plugin-btp/ws-reconnect.js:17:46)
    at WebSocket.emit (events.js:159:13)
    at WebSocket.finalize (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/ilp-plugin-btp/node_modules/ws/lib/WebSocket.js:182:41)
    at ClientRequest._req.on (/Users/paulrberg/Documents/projects/clones/moneyd-gui/node_modules/ilp-plugin-btp/node_modules/ws/lib/WebSocket.js:647:10)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:16333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sharafian** [comment]
Can I see your moneyd logs? This error could occur if moneyd weren't running or if it failed to start

**Comment by PaulRBerg** [comment]
Ah, it's fine. Indeed, `moneyd` failed to start. It might be a good thing to highlight 'Make sure you start Moneyd with --admin-api-port 7769' in the README.

**Comment by Sidewinder3514** [comment]
![image](https://user-images.githubusercontent.com/40026317/87870274-8a48c380-c9a6-11ea-9516-f02db1979fca.png)

**Comment by Sidewinder3514** [comment]
Could this be an issue with the Let's Encrypt centificate?
